{"msg_info":"2022-06-27 17:28:24:org.apache.flink.client.deployment.ClusterDeploymentException: Could not deploy Yarn job cluster.\norg.apache.flink.client.deployment.ClusterDeploymentException: Could not deploy Yarn job cluster.at org.apache.flink.yarn.YarnClusterDescriptor.deployJobCluster(YarnClusterDescriptor.java:501)at com.dtstack.engine.flink.FlinkClient.runPythonJobByPerJob(FlinkClient.java:592)at com.dtstack.engine.flink.FlinkClient.submitPyFlinkJobWithJar(FlinkClient.java:546)at com.dtstack.engine.flink.FlinkClient.submitPythonJobForStream(FlinkClient.java:505)at com.dtstack.engine.flink.FlinkClient.submitPythonJob(FlinkClient.java:483)at com.dtstack.engine.flink.FlinkClient.lambda$processSubmitJobWithType$3(FlinkClient.java:448)at com.dtstack.engine.base.util.SecurityUtils.login(SecurityUtils.java:80)at com.dtstack.engine.base.util.SecurityUtils.login(SecurityUtils.java:68)at com.dtstack.engine.flink.FlinkClient.processSubmitJobWithType(FlinkClient.java:431)at com.dtstack.engine.common.client.AbstractClient.submitJob(AbstractClient.java:48)at com.dtstack.engine.common.client.ClientProxy$2.execute(ClientProxy.java:89)at com.dtstack.engine.common.client.ClientProxy$2.execute(ClientProxy.java:85)at com.dtstack.engine.common.callback.ClassLoaderCallBackMethod.callbackAndReset(ClassLoaderCallBackMethod.java:13)at com.dtstack.engine.common.client.ClientProxy.lambda$submitJob$1(ClientProxy.java:85)at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.flink.client.program.ProgramInvocationException: The program caused an error: \n\nClasspath: [file:/opt/dtstack/112_flinkplugin/flink112_lib/flink-python_2.12-1.12.7.jar]\n\nSystem.out: (none)\n\nSystem.err: (none)at org.apache.flink.client.program.PackagedProgramUtils.generateException(PackagedProgramUtils.java:264)at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:172)at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:82)at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:117)at org.apache.flink.yarn.YarnClusterDescriptor.getJobGraph(YarnClusterDescriptor.java:1912)at org.apache.flink.yarn.YarnClusterDescriptor.deployInternal(YarnClusterDescriptor.java:571)at org.apache.flink.yarn.YarnClusterDescriptor.deployJobCluster(YarnClusterDescriptor.java:494)... 17 more\nCaused by: org.apache.flink.client.program.ProgramAbortException: java.lang.RuntimeException: Python process exits with code: 1at org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:124)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:224)at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:158)... 22 more\nCaused by: java.lang.RuntimeException: Python process exits with code: 1at org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:114)... 29 more\n"}
